# levibrooke.com

# Site settings
title: Levi Porter
email: hello@levibrooke.com
description: 
#url: http://levibrooke.com
url: http://localhost:4000

# Blog settings
permalink: /writing/:title/

# Collections
collections:
    work:
        output: true
        permalink: '/work/:path/'
        
# Analytics
google-analytics:
gosquared:

# Meta
google-verification:
meta-description: 

# Comments
disqus:

# Sass settings
sass:  
    sass_dir: _sass
    style: :nested
    
# Build settings
markdown: kramdown
highlighter: rouge

# Exclude
exclude:
- CNAME
- Gemfile
- Gemfile.lock
- .gitignore
- README.md
- .sass-cache
