name: Levi Porter
description: I create unique experiences for the web.
url: http://levibrooke.com

# blog settings
permalink: /articles/:title

# collections
collections:
    work:
        output: true
        
#defaults:
#    - scope:
#        path: ""
#        type: work
#    values:
#        layout: home

# plugins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom (RSS-like) feed of posts
  - jemoji
  - jekyll-redirect-from

# exclude
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME
    
# build settings
markdown: kramdown
highlighter: rouge
#sass:
#    sass_dir:
#    style:
