---
title: Levi Porter
timezone: Pacific/Honolulu
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  work:
    title: Work
    output: true
    permalink: "/work/:path/"
email: hello@levibrooke.com
description: 
url: http://levibrooke.com
permalink: "/writing/:title/"
google-analytics: 
gosquared: GSN-342265-Y
google-verification: 
meta-description: 
disqus: 
sass:
  sass_dir: _sass
  style: nested
markdown: kramdown
highlighter: rouge
exclude:
- CNAME
- Gemfile
- Gemfile.lock
- ".gitignore"
- README.md
- ".sass-cache"
